# Generated by Django 5.0.6 on 2026-07-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_agenttoken_restricted_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttoken',
            name='can_auto_approve',
            field=models.BooleanField(default=False, help_text='Allows pre-reviewed pipeline agents to create artifacts directly in approved or published states.'),
        ),
    ]
