# Generated by Django 6.0.7 on 2026-07-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_agent_agenttoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenttoken',
            name='token',
        ),
        migrations.AddField(
            model_name='agenttoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenttoken',
            name='token_hash',
            field=models.CharField(db_index=True, default='', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='agenttoken',
            name='token_prefix',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='agenttoken',
            name='scope',
            field=models.CharField(choices=[('read_only', 'Read Only'), ('read_write', 'Read Write')], default='read_write', max_length=20),
        ),
    ]
