# Generated by Django 5.0.2 on 2024-02-12 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_shareditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareditem',
            name='users',
            field=models.ManyToManyField(related_name='collab_items', to=settings.AUTH_USER_MODEL, verbose_name='all users that have a access to the file or folder'),
        ),
    ]
