# Generated by Django 6.0.7 on 2026-07-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_shareditem_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shareditem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='starreditem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='shareditem',
            name='object_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='starreditem',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
