# Generated by Django 5.0.6 on 2026-07-19 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('document', 'Document'), ('skill', 'Skill'), ('decision', 'Decision'), ('memory', 'Memory')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('inherit_permissions', models.BooleanField(default=True)),
                ('lifecycle_state', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('published', 'Published'), ('deprecated', 'Deprecated'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='draft', max_length=20)),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('indexed', 'Indexed'), ('stale', 'Stale'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('chunk_index', models.IntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('owner', 'Owner')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('relation_type', models.CharField(choices=[('derived_from', 'Derived From'), ('references', 'References'), ('uses', 'Uses'), ('produced_by', 'Produced By'), ('depends_on', 'Depends On'), ('supersedes', 'Supersedes'), ('reviewed_by', 'Reviewed By'), ('used_in', 'Used In')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.IntegerField()),
                ('file_instance', models.FileField(upload_to='artifact_versions/')),
                ('diff_content', models.TextField(blank=True)),
                ('commit_message', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='DecisionArtifact',
            fields=[
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='decision', serialize=False, to='artifacts.artifact')),
                ('decision_text', models.TextField()),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('decided', 'Decided'), ('superseded', 'Superseded')], default='proposed', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentArtifact',
            fields=[
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='document', serialize=False, to='artifacts.artifact')),
                ('file', models.FileField(upload_to='files')),
                ('format', models.CharField(default='markdown', help_text='markdown, pdf, docx, txt, etc.', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryArtifact',
            fields=[
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='memory', serialize=False, to='artifacts.artifact')),
                ('content', models.TextField()),
                ('scope', models.CharField(blank=True, help_text='agent_id, session_id, or collection-level', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillArtifact',
            fields=[
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='skill', serialize=False, to='artifacts.artifact')),
                ('skill_md_content', models.TextField(blank=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
        ),
    ]
