# Generated by Django 5.0.6 on 2026-07-19 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('artifacts', '0001_initial'),
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='collections.collection'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_artifacts', to='accounts.principal'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_artifacts', to='accounts.principal'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_artifacts', to='accounts.principal'),
        ),
        migrations.AddField(
            model_name='artifactchunk',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='artifacts.artifact'),
        ),
        migrations.AddField(
            model_name='artifactcomment',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='artifacts.artifact'),
        ),
        migrations.AddField(
            model_name='artifactcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.principal'),
        ),
        migrations.AddField(
            model_name='artifactpermission',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='artifacts.artifact'),
        ),
        migrations.AddField(
            model_name='artifactpermission',
            name='principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.principal'),
        ),
        migrations.AddField(
            model_name='artifactrelationship',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.principal'),
        ),
        migrations.AddField(
            model_name='artifactrelationship',
            name='from_artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='artifacts.artifact'),
        ),
        migrations.AddField(
            model_name='artifactrelationship',
            name='to_artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='artifacts.artifact'),
        ),
        migrations.AddField(
            model_name='artifactversion',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='artifacts.artifact'),
        ),
        migrations.AddField(
            model_name='artifactversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.principal'),
        ),
        migrations.AddField(
            model_name='artifactchunk',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='artifacts.artifactversion'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='artifacts.artifactversion'),
        ),
        migrations.AlterUniqueTogether(
            name='artifactpermission',
            unique_together={('artifact', 'principal')},
        ),
        migrations.AddIndex(
            model_name='artifactrelationship',
            index=models.Index(fields=['from_artifact', 'relation_type'], name='artifacts_a_from_ar_3b3632_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactrelationship',
            index=models.Index(fields=['to_artifact', 'relation_type'], name='artifacts_a_to_arti_e79366_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='artifactversion',
            unique_together={('artifact', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='artifactchunk',
            unique_together={('version', 'chunk_index')},
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['type'], name='artifacts_a_type_99e130_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['lifecycle_state'], name='artifacts_a_lifecyc_44ec7f_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['collection', 'type'], name='artifacts_a_collect_350314_idx'),
        ),
        migrations.AddConstraint(
            model_name='artifact',
            constraint=models.CheckConstraint(check=models.Q(('collection__isnull', True), ('inherit_permissions', True), _negated=True), name='no_inherit_without_collection'),
        ),
    ]
