# Generated by Django 5.0.6 on 2026-07-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='lifecycle_state',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('deprecated', 'Deprecated'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='draft', max_length=20),
        ),
    ]
