# Generated by Django 5.0.1 on 2024-01-31 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='owener',
            new_name='owner',
        ),
    ]
