# Generated by Django 6.0.7 on 2026-07-17 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_comment_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created_at']},
        ),
    ]
